### ISSUE TITLE
ose builds prior to 3.6 will fail openshift-ansible RPM build

### ISSUE THREAD

**Issue by markllama** [openshift/aos-cd-jobs#1446]
The openshift versions prior to 3.6 were not version and release locked to 2 fields.  The OIT RPM build system expects to apply a 2 field (3.N) version to all RPMs built and keep them in lockstep.

When building the using the `ose/Jenkins` job, the script pulls the version from the OSE rpm and then tries to apply it, all 5 fields to build the RPMs.  (currently only openshift-ansible for old builds).

One possible fix would be to allow oit rpms:build to accept --version 'tito' indicating that it would let the build system auto-increment in the same way that it has in older versions.

```
2018-06-07 10:49:38,955 INFO Registering source alias openshift-ansible: /home/jenkins/workspace/aos-cd-builds/build%2Fose/oit_working/sources/openshift-ansible
Traceback (most recent call last):
  File "/home/jenkins/workspace/aos-cd-builds/build%2Fose/enterprise-images//tools/bin/oit", line 1025, in <module>
    cli(obj={})
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/jenkins/workspace/aos-cd-builds/build%2Fose/enterprise-images//tools/bin/oit", line 124, in rpms_build
    results = results.get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
ocp_cd_tools.runtime.WrapException: 
Original traceback:
Traceback (most recent call last):
  File "/mnt/nfs/home/jenkins/workspace/aos-cd-builds/build%2Fose/enterprise-images/tools/src/ocp_cd_tools/runtime.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "/home/jenkins/workspace/aos-cd-builds/build%2Fose/enterprise-images//tools/bin/oit", line 122, in <lambda>
    version, release, terminate_event, scratch),
  File "/mnt/nfs/home/jenkins/workspace/aos-cd-builds/build%2Fose/enterprise-images/tools/src/ocp_cd_tools/rpmcfg.py", line 249, in build_rpm
    self.update_spec()
  File "/mnt/nfs/home/jenkins/workspace/aos-cd-builds/build%2Fose/enterprise-images/tools/src/ocp_cd_tools/rpmcfg.py", line 146, in update_spec
    major, minor, patch = self.version.split('.')
ValueError: too many values to unpack
```

**Comment by tbielawa** [comment]
from https://buildvm.openshift.eng.bos.redhat.com:8443/job/aos-cd-builds/job/build%252Fose/214/console

**Comment by jupierce** [comment]
I would lean toward having the rpm metadata decide how it is to be versioned. < 3.6 
```
content:
  source:
    alias: openshift-ansible
    specfile: openshift-ansible.spec
name: openshift-ansible
owners:
- sdodson@redhat.com
version: 
  mode: bump|adopt   (default to adopt)
```

'bump' would allow tito to bump the version as it already knows how to do. adopt would use what was specified on the command line.

**Comment by tbielawa** [comment]
Reverted in https://github.com/openshift/aos-cd-jobs/pull/1447

**Comment by markllama** [comment]
Reverted.  We can revisit for ose at our leisure

**Comment by markllama** [comment]
Yep, closed again.
