### ISSUE TITLE
sjb/hack/determine_install_upgrade_version.py errors

### ISSUE THREAD

**Issue by sjenning** [openshift/aos-cd-jobs#346]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/1489/console

```########## STARTING STAGE: INSTALL ORIGIN ##########
+ [[ -s /var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_install_update/workspace@4/activate ]]
+ source /var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_install_update/workspace@4/activate
++ export VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/9aea3b4f81e266b026e21975a3a6a5a1cfddd890
++ VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/9aea3b4f81e266b026e21975a3a6a5a1cfddd890
++ export PATH=/var/lib/jenkins/origin-ci-tool/9aea3b4f81e266b026e21975a3a6a5a1cfddd890/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ PATH=/var/lib/jenkins/origin-ci-tool/9aea3b4f81e266b026e21975a3a6a5a1cfddd890/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ unset PYTHON_HOME
++ export OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_install_update/workspace@4/.config
++ OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_install_update/workspace@4/.config
++ mktemp
+ script=/tmp/tmp.M96xyH5KQb
+ cat
+ chmod +x /tmp/tmp.M96xyH5KQb
+ scp -F ./.config/origin-ci-tool/inventory/.ssh_config /tmp/tmp.M96xyH5KQb openshiftdevel:/tmp/tmp.M96xyH5KQb
+ ssh -F ./.config/origin-ci-tool/inventory/.ssh_config -t openshiftdevel 'bash -l -c "/tmp/tmp.M96xyH5KQb"'
+ cd /data/src/github.com/openshift/aos-cd-jobs
++ cat ./PKG_NAME
+ pkg_name=origin
+ [[ origin == \o\r\i\g\i\n ]]
+ deployment_type=origin
+ echo origin
++ cat ORIGIN_BUILT_VERSION
+ sudo python sjb/hack/determine_install_upgrade_version.py origin-3.6.0-0.alpha.2.433.d922159.x86_64 --dependency_branch master
Traceback (most recent call last):
  File "sjb/hack/determine_install_upgrade_version.py", line 126, in <module>
    available_pkgs = sort_pkgs(available_pkgs)
  File "sjb/hack/determine_install_upgrade_version.py", line 73, in sort_pkgs
    exceptional_pkg["original_pkg"] = copy.deepcopy(pkg)
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 298, in _deepcopy_inst
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
  File "/usr/lib64/python2.7/copy_reg.py", line 93, in __newobj__
    return cls.__new__(cls, *args)
TypeError: object.__new__(thread.lock) is not safe, use thread.lock.__new__()
Exception AttributeError: AttributeError("'YumRepository' object has no attribute '_sack'",) in <bound method YumRepository.__del__ of <yum.yumRepo.YumRepository object at 0x2cc5590>> ignored
Exception AttributeError: AttributeError("'YumSqlitePackageSack' object has no attribute 'primarydb'",) in <bound method YumSqlitePackageSack.__del__ of <yum.sqlitesack.YumSqlitePackageSack object at 0x2cc54d0>> ignored
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: INSTALL ORIGIN [00h 00m 03s] ##########```

**Comment by sjenning** [comment]
https://github.com/openshift/aos-cd-jobs/commit/b80a5d8c6f5651dd14b3d8c2be5d2627d65e0aef introduced the `copy.deepcopy(pkg)` that results in the error.  It was reverted.  Then the revert was reverted.

@eparis

**Comment by stevekuznetsov** [comment]
@jhadvig

**Comment by stevekuznetsov** [comment]
I'll revert tonight.

**Comment by stevekuznetsov** [comment]
Revert would break PRs against non-master branches, which is not something we need during dev-cut. PR is open to fix this, we can finish it out tomorrow.

**Comment by sjenning** [comment]
Is this fix rolled out into the CI pipeline? I hit it again today
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/1489/console

**Comment by stevekuznetsov** [comment]
That job ran at `2017-06-20 18:31:45` -- the fix merged `2017-06-21 05:04:12`

**Comment by sjenning** [comment]
@stevekuznetsov gah my bad.  link was too the old result still.  nevermind!
